### ISSUE TITLE
Make it work in DMs

### ISSUE THREAD

**Issue by theLMGN** [marijuanARM/autotss#3]
Just see Sileo #bot-commands right now and you'll see why I'm requesting this

**Comment by marijuanARM** [comment]
While I'd like to, I currently limit AutoTSS to servers only, as I'm wanting to keep the load on AutoTSS as light as possible (you must be in a server with AutoTSS, or else it won't save blobs for your device & will delete those blobs.) A workaround is to create your own Discord server, add AutoTSS to there, and then add your devices there. Then, as long as you stay in the Sileo discord, your blobs will be saved (even if you delete the server you created for AutoTSS.)

**Comment by theLMGN** [comment]
Would it not be possible to check if the user shares a server with the bot before running any DM commands?
